### ISSUE TITLE
哥哥好

### ISSUE THREAD

**Issue by xiaopohou** [jerrytang67/SoMall#21]
看了你的这个项目我非常喜欢，喜欢你的风格，后端开源的地址在哪 我想学习下！

**Comment by jerrytang67** [comment]
小程序,管理后台和后端都在这个项目里

**Comment by xiaopohou** [comment]
谢谢哥！我去看看！

**Comment by xiaopohou** [comment]
哥，有微信吗，方便加一个微信吗

**Comment by jerrytang67** [comment]
有什么需求这里提就好

**Comment by xiaopohou** [comment]
好的好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JerryTang <notifications@github.com&gt;
发送时间: 2020年4月1日 09:55
收件人: jerrytang67/SoMall <SoMall@noreply.github.com&gt;
抄送: 老赵 <393331943@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[jerrytang67/SoMall] 哥哥好 (#21)
