### ISSUE TITLE
有文档吗?想参与进来

### ISSUE THREAD

**Issue by bxjg1987** [jerrytang67/SoMall#22]
我目前也在做电商模块（https://gitee.com/bxjg1987/abp/tree/master/src/shop/BXJG.Shop.Core），不过用的老板abp。SoMall有文档吗，先学习下，对vNext不太熟

**Comment by jerrytang67** [comment]
暂时整个架构都和ABP的微服务架构差不多,那个能懂就能开发.欢迎加入进来.

**Comment by jerrytang67** [comment]
有好的功能意见可以加我QQ138868998
