### ISSUE TITLE
[Issue] variable 'loadingText' is undefined

### ISSUE THREAD

**Issue by xman086** [jerrytang67/SoMall#27]
file path: src/pages/index/index.vue
error: [Vue warn]: Property or method "loadingText" is not defined on the instance but referenced during render.

**Comment by jerrytang67** [comment]
which folder's vue project

**Comment by xman086** [comment]
SoMall-master\uni-mall\src\pages\index\index.vue
and line 58

**Comment by jerrytang67** [comment]
this is not use now, thxi wil remove this line
